name: Check lint

on:
  pull_request:
    branches:
      - develop # should rename this branch to your project's situation.
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: |
          npm install
      
      # should create the script "lint" in package.json. `"lint": "eslint . --ext .ts"`
      - name: Check lint
        run: |
          npm run lint 

      # should create the script "build" in package.json.
      - name: Check build
        run: |
          npm run build
