name: Check lint

on:
  pull_request:
    branches:
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: |
          npm install
      
      - name: Check lint
        run: |
          npm run lint

      - name: Check build
        run: |
          npm run build:develop
