name: cdk deploy DEVELOP

on:
  push:
    branches:
      - develop # should rename this branch to your project's situation.

jobs:
  develop_deployment:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install

      # should create the script "build" in package.json.
      - name: DEV Build Code
        run: |
          npm run build

      - name: Setup awscli v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # should create those secrets `DISTRIBUTION`, `STORAGE_BUCKET`, `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` in github repository before run this action.
      - name: Identity Check
        run: aws sts get-caller-identity
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload S3
        run: |
          aws s3 sync --exact-timestamps --delete build/ s3://$AWS_STORAGE_BUCKET
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create Invalidation
        run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION --paths '/*'
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
